[[constraint]]
    name = "github.com/gomodule/redigo"
    version = "2.0.0"

[[constraint]]
    name = "github.com/onsi/ginkgo"
    version = "^1.4"

[[constraint]]
    name = "github.com/onsi/gomega"
    version = "^1.3"

[[constraint]]
    name = "github.com/rafaeljusto/redigomock"
    branch = "master"
